### main  page
GET http://localhost:3000/

### all posts
GET http://localhost:3000/api/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFwcHA1QGFhcHA1LmNvbSIsInN1YiI6MjMsImlhdCI6MTcwNTQwNDY4OSwiZXhwIjoxNzA1NDA4Mjg5fQ.waykyOm8HclFDr64Sp_ewEf1PTsliMqzP5PiRybKNzg

### get one post
GET http://localhost:3000/api/posts/3 OR 1=1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFwcHA1QGFhcHA1LmNvbSIsInN1YiI6MjMsImlhdCI6MTcwNTQwNDY4OSwiZXhwIjoxNzA1NDA4Mjg5fQ.waykyOm8HclFDr64Sp_ewEf1PTsliMqzP5PiRybKNzg


### delete
DELETE  http://localhost:3000/api/posts/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFwcHA1QGFhcHA1LmNvbSIsInN1YiI6MjMsImlhdCI6MTcwNTQxMjg0NiwiZXhwIjoxNzA1NDE2NDQ2fQ.3R4HGnCkbevYOYL2h7m3JbGkbT4jUH__G5pn0fxWnbA

### POST CREATE POST
POST  http://localhost:3000/api/posts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFwcHA1QGFhcHA1LmNvbSIsInN1YiI6MjMsImlhdCI6MTcwNTQwNDY4OSwiZXhwIjoxNzA1NDA4Mjg5fQ.waykyOm8HclFDr64Sp_ewEf1PTsliMqzP5PiRybKNzg0

{
  "title": "controller",
  "author": "Jane Dow",
  "date": "2023-12-28",
  "content": "Some important msg",
  "cat_id": 5
}


### all books
GET http://localhost:3000/api/books

### get one book
GET http://localhost:3000/api/books/7 OR 1=1

### delete book
DELETE  http://localhost:3000/api/books/5

### POST CREATE books
POST  http://localhost:3000/api/books
Content-Type: application/json

{
  "title": "Name 10",
  "author": "Author 10",
  "year": 1990
}

### all categories
GET http://localhost:3000/api/categories

### LOGIN user
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "appp5@aapp5.com",
  "password": "12355"
}

### REGISTER user
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "email": "surnam@surname.com",
  "password": "12355"
}

### GET comments by postId
GET http://localhost:3000/api/comments/post/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFwcHA1QGFhcHA1LmNvbSIsInN1YiI6MjMsImlhdCI6MTcwNTQwNDY4OSwiZXhwIjoxNzA1NDA4Mjg5fQ.waykyOm8HclFDr64Sp_ewEf1PTsliMqzP5PiRybKNzg

### POST comments

POST http://localhost:3000/api/comments
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFwcHA1QGFhcHA1LmNvbSIsInN1YiI6MjMsImlhdCI6MTcwNTQwNDY4OSwiZXhwIjoxNzA1NDA4Mjg5fQ.waykyOm8HclFDr64Sp_ewEf1PTsliMqzP5PiRybKNzg

{
  "author": "surname@surname.com",
  "comment": "nice one",
  "post_id": "5"
}