### main  page
GET http://localhost:3000/

### all posts
GET http://localhost:3000/api/posts

### get one post
GET http://localhost:3000/api/posts/33 OR 1=1

### delete
DELETE  http://localhost:3000/api/posts/1

### POST CREATE POST
POST  http://localhost:3000/api/posts
Content-Type: application/json

{
  "title": "Post from rest",
  "author": "Jane Dow",
  "date": "2023-12-28",
  "content": "Some important msg",
  "cat_id": 5
}


### all books
GET http://localhost:3000/api/books

### get one book
GET http://localhost:3000/api/books/7 OR 1=1

### delete book
DELETE  http://localhost:3000/api/books/5

### POST CREATE books
POST  http://localhost:3000/api/books
Content-Type: application/json

{
  "title": "Name 10",
  "author": "Author 10",
  "year": 1990
}

### all categories
GET http://localhost:3000/api/categories

### LOGIN user
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "james@bond.com",
  "password": "12345"
}

### REGISTER user
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "email": "appp5@aapp5.com",
  "password": "12355"
}